name: CI Pipeline

on: 
  push:
    branches:
      - flow
  pull_request:
    branches:
      - flow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a simple script
        run: echo "CI pipeline is workin!"
